### ISSUE TITLE
Use GPG to sign commits

### ISSUE THREAD

**Issue by edulix** [mhutchinson/mhutchinson-distributor#152528]
Although it might be slow and thus not possible,  it might be interesting to sign the commits so that their source is verifiable https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by mhutchinson** [comment]
This repository is very busy with automation and the only way I could manage notification spam was to disable notifications. Thus, I've only just seen this. Sorry for the delay in replying!

The commits don't need to be signed as the contents of the commits are signed. It doesn't matter _who_ performs the mechanism of the commit, as the content signature will be verified for this to be merged. I'm not sure that adding commit signing would provide any benefit.

I'll close this, but if you think there's something I've missed then I'm very happy to discuss. I see that you're on the Trillian Slack channel so message me via there and we can work this out 👍
